Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> from sudoku import*
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from sudoku import*
ModuleNotFoundError: No module named 'sudoku'
>>> from sudoku import *
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    from sudoku import *
ModuleNotFoundError: No module named 'sudoku'
>>> asudoku=sudoku()
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    asudoku=sudoku()
NameError: name 'sudoku' is not defined
>>> asudoku.generate()
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    asudoku.generate()
NameError: name 'asudoku' is not defined
>>> asudoku.display()
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    asudoku.display()
NameError: name 'asudoku' is not defined
>>> asudoku=sudoku()
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    asudoku=sudoku()
NameError: name 'sudoku' is not defined
>>> asudoku.makepuzzle(40)
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    asudoku.makepuzzle(40)
NameError: name 'asudoku' is not defined
>>> asudoku.display()
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    asudoku.display()
NameError: name 'asudoku' is not defined
>>> asudoku.solved()
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    asudoku.solved()
NameError: name 'asudoku' is not defined
>>> asudoku.solve()
Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    asudoku.solve()
NameError: name 'asudoku' is not defined
>>> asudoku.display()
Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    asudoku.display()
NameError: name 'asudoku' is not defined
>>> 
